services:
  db-auth-service:
    restart: always
    image: postgres:alpine3.21
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    restart: always
    image: redis:7.4.2-alpine
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend: