services:
  auth-service:
    restart: always
    build: ./auth-service
    ports:
      - "9091:9091"
    depends_on:
      - db-auth-service
      - redis
    networks:
      - backend

  db-auth-service:
    restart: always
    image: postgres:alpine3.21
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./docker/auth-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  content-service:
    restart: always
    build: ./content-service
    ports:
      - "9092:9092"
    networks:
      - backend
    depends_on:
      - db-content-service
      - rabbitmq
      - redis

  db-content-service:
    restart: always
    image: postgres:alpine3.21
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./docker/content-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - backend

  worker:
    build: ./worker-service
    restart: always
    depends_on:
      - rabbitmq
    ports:
      - "8008:8080"
    networks:
      - backend

  redis:
    restart: always
    image: redis:7.4.2-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 3

  notification-service:
    build: ./notification-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

networks:
  backend:
